const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
let db=new Map(),fallo=null,escrituras=0,ignorarMarca=false;
const copia=x=>x==null?null:structuredClone(x);
const cliente={from(tabla){assert.equal(tabla,'torneos_control');let tipo='lectura',cambios={},filtros=[];const q={select(){return q},eq(c,v){filtros.push([c,v]);return q},abortSignal(){return q},update(d){tipo='cambio';cambios=d;return q},insert(d){tipo='alta';cambios=d;return q},async maybeSingle(){return ejecutar()},async single(){return ejecutar()}};async function ejecutar(){if(fallo)return {data:null,error:{code:fallo}};const id=tipo==='alta'?cambios.id:filtros.find(([c])=>c==='id')[1];let fila=db.get(id);if(tipo==='lectura'){const snapshot=copia(fila);await Promise.resolve();return {data:snapshot,error:null}}escrituras++;if(tipo==='alta'){if(fila)return {data:null,error:{code:'23505'}};fila={id,pagaron_ids:[],asistieron_ids:[],created_at:'2026-10-07T12:00:00Z',...cambios}}else{if(!fila||!filtros.every(([c,v])=>c==='id'?fila[c]===v:JSON.stringify(fila[c])===v))return {data:null,error:null};fila={...fila,...(ignorarMarca?{actualizado_en:cambios.actualizado_en}:cambios)}}db.set(id,fila);return {data:copia(fila),error:null}}return q}};
require.extensions['.ts']=(m,f)=>{if(path.basename(f)==='supabase.ts'){m.exports={supabase:cliente};return}m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f)};
const {establecerMarcaTorneo}=require('../lib/controlTorneos.ts');
function reiniciar(fila){db=new Map(fila?[[fila.id,fila]]:[]);fallo=null;escrituras=0;ignorarMarca=false}
const base=()=>({id:'t',pagaron_ids:[],asistieron_ids:[],created_at:'2026-10-07T12:00:00Z',actualizado_en:'2026-10-07T12:00:00Z'});
test('Marcar, releer y desmarcar un pago conserva el estado confirmado',async()=>{reiniciar();await establecerMarcaTorneo('t','pagaron_ids','a',true);assert.deepEqual(db.get('t').pagaron_ids,['a']);const recarga=await cliente.from('torneos_control').select('*').eq('id','t').maybeSingle();assert.deepEqual(recarga.data.pagaron_ids,['a']);await establecerMarcaTorneo('t','pagaron_ids','a',false);assert.deepEqual(db.get('t').pagaron_ids,[])});
test('Dos altas de pagos simultáneas se combinan sin sobrescribir una de ellas',async()=>{reiniciar();await Promise.all([establecerMarcaTorneo('t','pagaron_ids','a',true),establecerMarcaTorneo('t','pagaron_ids','b',true)]);assert.deepEqual([...db.get('t').pagaron_ids].sort(),['a','b'])});
test('Dos pagos sobre el mismo registro se combinan después de un conflicto',async()=>{reiniciar(base());await Promise.all([establecerMarcaTorneo('t','pagaron_ids','a',true),establecerMarcaTorneo('t','pagaron_ids','b',true)]);assert.deepEqual([...db.get('t').pagaron_ids].sort(),['a','b'])});
test('Reintentar el mismo valor no alterna ni duplica un pago',async()=>{reiniciar();await establecerMarcaTorneo('t','pagaron_ids','a',true);const antes=escrituras;await establecerMarcaTorneo('t','pagaron_ids','a',true);assert.equal(escrituras,antes);assert.deepEqual(db.get('t').pagaron_ids,['a'])});
test('Pagos y asistencia simultáneos mantienen los dos cambios',async()=>{reiniciar(base());await Promise.all([establecerMarcaTorneo('t','pagaron_ids','a',true),establecerMarcaTorneo('t','asistieron_ids','b',true)]);assert.deepEqual(db.get('t').pagaron_ids,['a']);assert.deepEqual(db.get('t').asistieron_ids,['b'])});
test('Una tabla sin activar, una caída de red y una denegación no simulan guardados',async()=>{for(const codigo of ['PGRST205','NETWORK','42501']){reiniciar(base());fallo=codigo;await assert.rejects(establecerMarcaTorneo('t','pagaron_ids','a',true),codigo==='PGRST205'?/no está habilitado/:/no está confirmado/);assert.deepEqual(db.get('t').pagaron_ids,[]);assert.equal(escrituras,0)}});
test('Una respuesta del servidor que no contiene la marca no se presenta como guardada',async()=>{reiniciar(base());ignorarMarca=true;await assert.rejects(establecerMarcaTorneo('t','pagaron_ids','a',true),/no confirmó/)});
