const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {Chess}=require('chess.js');const {PartidaPractica,respuestaSuave}=require('../lib/partidaPractica.ts');const {ESQUEMA_HIPOPOTAMO,jugadasHipopotamo}=require('../lib/hipopotamo.ts');const {MotorPractica}=require('../lib/motorPractica.ts');

test('Fonchi sólo puede ser el rival negro y no recibe aleatoriedad del nivel suave',()=>{assert.throws(()=>new PartidaPractica('b','club','fonchi'),/negras/);const p=new PartidaPractica('w','suave','fonchi');p.moverJugador('e2','e4');assert.equal(respuestaSuave(p,'g7g6',()=>0),'g7g6');assert.equal(PartidaPractica.recuperar({...p.guardar(),color:'b'}),null);});
test('Guarda el rival, retoma su apertura y mantiene compatibilidad con partidas anteriores',()=>{const p=new PartidaPractica('w','club','fonchi');p.moverJugador('e2','e4');p.moverBot('g7g6');p.moverJugador('d2','d4');const r=PartidaPractica.recuperar(p.guardar());assert.equal(r.perfil,'fonchi');assert.deepEqual(jugadasHipopotamo(r.ajedrez),jugadasHipopotamo(p.ajedrez));assert.match(r.pgn(),/Black "Fonchi y el Hipopótamo/);assert.ok(r.deshacer());assert.equal(r.jugadas.length,2);const vieja=new PartidaPractica().guardar();delete vieja.perfil;assert.equal(PartidaPractica.recuperar(vieja).perfil,'stockfish');assert.equal(PartidaPractica.recuperar({...vieja,perfil:'otro'}),null);});
test('Responde e4, d4, c4 y Cf3 con g6, sin escoger una Siciliana o un centro de e5',()=>{for(const blanca of ['e4','d4','c4','Nf3']){const c=new Chess();c.move(blanca);assert.deepEqual(jugadasHipopotamo(c),['g7g6']);}});
test('Completa las diez jugadas del Hipopótamo frente a desarrollo tranquilo y luego libera el medio juego',()=>{const c=new Chess();for(const blanca of ['e4','d4','Nf3','Nc3','Be2','O-O','Re1','Bf1','h3','a3']){c.move(blanca);const opciones=jugadasHipopotamo(c);assert.ok(opciones?.length,blanca);const esquema=ESQUEMA_HIPOPOTAMO.find(m=>opciones.includes(m));assert.ok(esquema);c.move(esquema);}for(const [s,t] of [['g6','p'],['b6','p'],['d6','p'],['e6','p'],['a6','p'],['h6','p'],['g7','b'],['b7','b'],['d7','n'],['e7','n']])assert.equal(c.get(s).type,t,s);c.move('a4');assert.equal(jugadasHipopotamo(c),undefined);});
test('Ante un jaque deja al motor elegir la defensa legal y el esquema se reanuda después',()=>{const c=new Chess();for(const san of ['e4','g6','d4','d6','Bb5+'])c.move(san);assert.equal(c.isCheck(),true);const defensas=jugadasHipopotamo(c);assert.ok(defensas.includes('b8d7'));assert.ok(!defensas.includes('a7a6'));c.move('Nd7');c.move('Nf3');const m=jugadasHipopotamo(c);assert.ok(m?.length);assert.ok(m.every(uci=>c.moves({verbose:true}).some(x=>x.from+x.to+(x.promotion||'')===uci)));assert.ok(!m.includes('b8d7'));});
test('Permite reaccionar a una captura y un avance central sin inventar una jugada ilegal',()=>{const c=new Chess();for(const san of ['e4','g6','d4','d6','e5'])c.move(san);const m=jugadasHipopotamo(c);assert.ok(m.includes('d6e5'));assert.ok(m.every(uci=>c.moves({verbose:true}).some(x=>x.from+x.to+(x.promotion||'')===uci)));});
test('No permite mate del pastor por seguir la formación: restringe a defensas seguras',()=>{const c=new Chess();for(const san of ['e4','e5','Bc4','Nc6','Qh5'])c.move(san);const m=jugadasHipopotamo(c);assert.ok(m?.length);assert.ok(!m.includes('d7d6'));assert.ok(!m.includes('b7b6'));for(const uci of m){c.move(uci);assert.ok(!c.moves().some(s=>s.endsWith('#')),uci);c.undo();}});

class WorkerFalso extends EventTarget{commands=[];postMessage(c){this.commands.push(c);if(c==='uci')queueMicrotask(()=>this.emitir('uciok'));if(c==='isready')queueMicrotask(()=>this.emitir('readyok'));}terminate(){}emitir(data){this.dispatchEvent(new MessageEvent('message',{data}));}}
async function responder(w,m,history,pista,options,uci){const p=m.buscar(history,'club',pista,options);await new Promise(r=>setImmediate(r));const commands=w.commands.splice(0);w.emitir('bestmove '+uci);assert.equal(await p,uci);return commands;}
test('Configura UCI_Elo 1850 y restringe apertura; pistas y práctica libre restablecen su fuerza',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;w.commands=[];try{let commands=await responder(w,m,['e2e4'],false,{elo:1850,searchmoves:['g7g6']},'g7g6');assert.ok(commands.includes('setoption name UCI_LimitStrength value true'));assert.ok(commands.includes('setoption name UCI_Elo value 1850'));assert.ok(commands.includes('go movetime 1000 searchmoves g7g6'));commands=await responder(w,m,[],true,{elo:1850,searchmoves:['g7g6']},'e2e4');assert.ok(commands.includes('setoption name UCI_LimitStrength value false'));assert.equal(commands.some(c=>c.includes('searchmoves')),false);commands=await responder(w,m,['e2e4'],false,{elo:1850},'g7g6');assert.ok(commands.includes('setoption name UCI_LimitStrength value true'));commands=await responder(w,m,['e2e4'],false,{},'e7e5');assert.ok(commands.includes('setoption name UCI_LimitStrength value false'));assert.ok(commands.includes('setoption name Skill Level value 4'));await assert.rejects(m.buscar([], 'club',false,{searchmoves:[]}),/Apertura/);await assert.rejects(m.buscar([], 'club',false,{searchmoves:['x7x6']}),/Apertura/);}finally{m.destruir();}});
