const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {Chess}=require('chess.js');const {DecodificadorPegasus,ColaPegasus}=require('../lib/pegasusProtocolo.ts');
const {RegistroPegasus,ocupacion,recuperarPartida,hacerJugadaManual}=require('../lib/registroPegasus.ts');
const {ejecutarPruebaPegasus,eventosJugada}=require('../lib/pruebaPegasus.ts');const {ColaTransmision}=require('../lib/colaTransmision.ts');
const vista=bytes=>new DataView(Uint8Array.from(bytes).buffer);
test('BLE reconstruye una foto dividida en fragmentos de 20 bytes y mensajes concatenados',()=>{
  const recibidos=[],d=new DecodificadorPegasus(m=>recibidos.push(m));const trama=[0x86,0,67,...ocupacion(new Chess()).map(Number),0x8e,0,5,52,0,0x8e,0,5,36,1];
  for(let i=0;i<trama.length;i+=20)d.agregar(vista(trama.slice(i,i+20)));
  assert.equal(recibidos.length,3);assert.equal(recibidos[0].ocupado.length,64);assert.deepEqual(recibidos[1],{tipo:'casilla',indice:52,ocupada:false});
});
test('BLE no entrega fotos parciales ni acepta índices de casilla inválidos',()=>{const r=[],d=new DecodificadorPegasus(m=>r.push(m));d.agregar(vista([0x86,0,67,1,0]));assert.equal(r.length,0);d.reiniciar();d.agregar(vista([0x8e,0,5,99,1,0x8e,0,5,0,0]));assert.equal(r.length,1);});
test('Cola GATT serializa y continúa después de una operación fallida',async()=>{const cola=new ColaPegasus(),orden=[];let activos=0,maximo=0;await Promise.allSettled([1,2,3].map(i=>cola.ejecutar(async()=>{maximo=Math.max(maximo,++activos);orden.push(i);await Promise.resolve();activos--;if(i===2)throw Error('fallo');})));assert.equal(maximo,1);assert.deepEqual(orden,[1,2,3]);cola.cerrar();await assert.rejects(cola.ejecutar(async()=>{}));});
for(const rapida of [false,true])for(const orden of ['atacante','atacada','alternar'])test(`Partida completa con capturas ${orden} y velocidad ${rapida?'rápida':'normal'}`,()=>{const r=ejecutarPruebaPegasus(rapida,orden);assert.equal(r.jugadas.length,33);assert.equal(r.jugadas.at(-1),'Rd8#');assert.equal(recuperarPartida(r).fen(),r.fen);});
function preparar(fen){const chess=new Chess(fen),s=new RegistroPegasus();s.foto(ocupacion(chess),1000);assert.equal(s.evaluar(chess,1000).tipo,'sin-cambio');return {chess,s};}
test('La foto completa repara un evento perdido en mitad del seguimiento',()=>{const {chess,s}=preparar();s.campo('e2',false,1100);const real=new Chess();real.move('e4');s.foto(ocupacion(real),1300);const l=s.evaluar(chess,2300);assert.equal(l.tipo,'jugada');assert.equal(l.candidatos[0].san,'e4');});
test('Una captura ambigua sin destino observado pide elegir en vez de inventar',()=>{const {chess,s}=preparar('4k3/8/8/3n1n2/4P3/8/8/4K3 w - - 0 1');const real=new Chess(chess.fen());real.move('exd5');s.foto(ocupacion(real),1500);const l=s.evaluar(chess,3000);assert.equal(l.tipo,'elegir');assert.equal(l.candidatos.length,2);assert.equal(chess.history().length,0);});
test('Captura al paso en ambos órdenes conserva la casilla de la pieza retirada',()=>{for(const orden of [false,true]){const {chess,s}=preparar('4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 1'),real=new Chess(chess.fen()),m=real.move('exd6');for(const [c,v] of eventosJugada(m,orden))s.campoConPartida(chess,c,v,1500);const l=s.evaluar(chess,3000);assert.equal(l.tipo,'jugada');assert.equal(l.candidatos[0].san,'exd6');}});
test('Coronación no asume dama: exige elegir las cuatro piezas',()=>{const {chess,s}=preparar('4k3/P7/8/8/8/8/8/4K3 w - - 0 1');s.campo('a7',false,1500);s.campo('a8',true,1550);const l=s.evaluar(chess,3000);assert.equal(l.tipo,'elegir');assert.equal(l.candidatos.length,4);s.confirmarJugada(chess,l.candidatos.find(m=>m.promotion==='n').san);assert.equal(chess.get('a8').type,'n');});
test('Enroque con torre primero espera al rey; ambos colores y lados',()=>{for(const turno of ['w','b'])for(const lado of ['O-O','O-O-O']){const {chess,s}=preparar(`r3k2r/8/8/8/8/8/8/R3K2R ${turno} KQkq - 0 1`),real=new Chess(chess.fen()),m=real.move(lado);const eventos=eventosJugada(m);for(const [c,v] of eventos.slice(2))s.campoConPartida(chess,c,v,1500);assert.equal(s.evaluar(chess,2450).tipo,'moviendo');assert.equal(s.evaluar(chess,3600).tipo,'elegir');for(const [c,v] of eventos.slice(0,2))s.campoConPartida(chess,c,v,4000);assert.equal(s.evaluar(chess,5000).candidatos[0].san, lado);}});
test('Acomodar una pieza y devolverla, duplicados y desajustes no crean jugadas',()=>{const {chess,s}=preparar();s.campo('e2',false,1100);s.campo('e2',true,1200);s.campo('e2',true,1250);assert.equal(s.evaluar(chess,3000).tipo,'sin-cambio');s.campo('a1',false,3100);assert.equal(s.evaluar(chess,5000).tipo,'desajuste');assert.equal(chess.history().length,0);});
test('Reconectar exige verificar la posición, sin borrar las jugadas anteriores',()=>{const {chess,s}=preparar();chess.move('e4');s.iniciarConexion();s.foto(ocupacion(new Chess()),1500);assert.equal(s.evaluar(chess,3000).tipo,'acomodar');assert.equal(chess.history().length,1);s.foto(ocupacion(chess),3100);assert.equal(s.evaluar(chess,3200).tipo,'sin-cambio');});
test('Recupera PGN, posición especial y resultado; rechaza historiales incompatibles',()=>{const c=new Chess('4k3/P7/8/8/8/8/8/4K3 w - - 0 1');hacerJugadaManual(c,'a7a8n');c.header('Result','1/2-1/2');const r=recuperarPartida({fen:c.fen(),pgn:c.pgn()});assert.equal(r.history().length,1);assert.ok(r.pgn().includes('1/2-1/2'));assert.throws(()=>recuperarPartida({jugadas:['e4'],fen:new Chess().fen()}));});
test('Publicación conserva el estado nuevo durante una escritura y reintenta un fallo',async()=>{const escritos=[],estados=[];let liberar;const cola=new ColaTransmision(async d=>{escritos.push(d);if(d===1)await new Promise(r=>liberar=r);},s=>estados.push(s));const a=cola.agregar(1);await Promise.resolve();const b=cola.agregar(2),c=cola.agregar(3);liberar();assert.equal(await a,true);assert.equal(await b,true);assert.equal(await c,true);assert.deepEqual(escritos,[1,3]);assert.equal(estados.at(-1),'guardado');let falla=true;const reintento=new ColaTransmision(async()=>{if(falla)throw Error('red');},()=>{});assert.equal(await reintento.agregar({pgn:'partida completa',activa:false}),false);falla=false;await reintento.reintentar();});
test('Ciento veinte medias jugadas rápidas, incluso posiciones repetidas, conservan toda la planilla',()=>{const {chess,s}=preparar(),real=new Chess();let ahora=1000;for(let i=0;i<30;i++)for(const san of ['Nf3','Nf6','Ng1','Ng8']){const m=real.move(san);for(const [c,v] of eventosJugada(m))s.campoConPartida(chess,c,v,ahora+=30);s.foto(ocupacion(real),ahora);}const ultima=s.evaluar(chess,ahora+2500);assert.equal(ultima.tipo,'jugada');s.confirmarJugada(chess,ultima.candidatos[0].san);assert.equal(chess.history().length,120);assert.deepEqual(chess.history(),real.history());});
test('Levantar una atacante sin apoyarla no registra una captura aunque sea la única legal',()=>{const {chess,s}=preparar('4k3/8/8/3n4/4P3/8/8/4K3 w - - 0 1');s.campoConPartida(chess,'e4',false,1500);assert.notEqual(s.evaluar(chess,3500).tipo,'jugada');assert.equal(chess.history().length,0);});
test('Controlador BLE lee notificaciones fragmentadas y limpia una desconexión real',async()=>{
  const {conectarPegasus,SERVICE_UUID,RX_CHARACTERISTIC_UUID}=require('../lib/pegasus.ts');const anteriorNavigator=Object.getOwnPropertyDescriptor(globalThis,'navigator'),anteriorWindow=globalThis.window;
  class Caracteristica extends EventTarget{async startNotifications(){return this;}async readValue(){return vista([85]);}async writeValue(v){escritos.push([...v]);await Promise.resolve();}enviar(bytes){this.value=vista(bytes);this.dispatchEvent(new Event('characteristicvaluechanged'));}}
  const escritos=[],rx=new Caracteristica(),tx=new Caracteristica(),battery=new Caracteristica(),device=new EventTarget(),server={async connect(){return this;},async getPrimaryService(uuid){return {async getCharacteristic(id){return uuid==='battery_service'?battery:id===RX_CHARACTERISTIC_UUID?rx:tx;}};},disconnect(){device.dispatchEvent(new Event('gattserverdisconnected'));}};device.gatt=server;const eventos=[];
  Object.defineProperty(globalThis,'navigator',{configurable:true,value:{bluetooth:{async requestDevice(opciones){assert.equal(opciones.filters[0].services[0],SERVICE_UUID);return device;}}}});globalThis.window={isSecureContext:true};
  try{const enlace=await conectarPegasus({onLog:()=>{},onPiezaLevantada:c=>eventos.push(c),onPiezaApoyada:()=>{},onVolcadoTablero:()=>{},onDesconectado:()=>eventos.push('desconectado')});rx.enviar([0x8e,0]);rx.enviar([5,52,0]);assert.deepEqual(eventos,['e2']);await Promise.all([enlace.pedirEstado(),enlace.pedirEstado()]);device.dispatchEvent(new Event('gattserverdisconnected'));const cantidad=escritos.length;rx.enviar([0x8e,0,5,53,0]);await enlace.pedirEstado();assert.equal(escritos.length,cantidad);assert.deepEqual(eventos,['e2','desconectado']);}finally{if(anteriorNavigator)Object.defineProperty(globalThis,'navigator',anteriorNavigator);else delete globalThis.navigator;globalThis.window=anteriorWindow;}
});

test('Una corrección abandonada no confirma la transición al tocar una pieza rival incompatible',()=>{const {chess,s}=preparar();s.campoConPartida(chess,'g1',false,1100);s.campoConPartida(chess,'f3',true,1150);s.campoConPartida(chess,'f3',false,1200);s.campoConPartida(chess,'e7',false,1250);assert.equal(chess.history().length,0);assert.equal(s.evaluar(chess,3000).tipo,'desajuste');});
