const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {PartidaPractica,respuestaSuave}=require('../lib/partidaPractica.ts');const {MotorPractica}=require('../lib/motorPractica.ts');
function serie(p,jugadas){for(const uci of jugadas){const ok=p.turnoJugador?p.moverJugador(uci.slice(0,2),uci.slice(2,4),uci[4]):p.moverBot(uci);assert.ok(ok,uci);}}
test('Bloquea jugadas ilegales, turnos dobles y respuestas del bot fuera de turno',()=>{const p=new PartidaPractica();assert.equal(p.moverBot('e2e4'),false);assert.equal(p.moverJugador('e2','e5'),false);assert.equal(p.moverJugador('e2','e4'),true);assert.equal(p.moverJugador('d2','d4'),false);assert.equal(p.moverBot('e7e5'),true);assert.equal(p.jugadas.length,2);});
test('Con negras el bot abre y no se puede deshacer su única jugada inicial',()=>{const p=new PartidaPractica('b');assert.equal(p.turnoJugador,false);assert.ok(p.moverBot('e2e4'));assert.equal(p.deshacer(),false);assert.equal(p.turnoJugador,true);});
test('Deshacer durante el pensamiento vuelve una media jugada; después de responder vuelve dos',()=>{const p=new PartidaPractica();p.moverJugador('e2','e4');assert.ok(p.deshacer());assert.equal(p.jugadas.length,0);serie(p,['e2e4','e7e5','g1f3','b8c6']);assert.ok(p.deshacer());assert.deepEqual(p.jugadas,['e2e4','e7e5']);assert.equal(p.turnoJugador,true);});
test('Enroque legal mueve rey y torre y no pierde sus derechos al recuperar',()=>{const p=new PartidaPractica();serie(p,['e2e4','e7e5','g1f3','b8c6','f1c4','g8f6']);const r=PartidaPractica.recuperar(p.guardar());assert.ok(r.moverJugador('e1','g1'));assert.equal(r.ajedrez.get('f1').type,'r');assert.equal(r.ajedrez.get('h1'),undefined);});
test('Captura al paso se aplica y se restaura desde el historial completo',()=>{const p=new PartidaPractica();serie(p,['e2e4','a7a6','e4e5','d7d5']);const r=PartidaPractica.recuperar(p.guardar());assert.ok(r.moverJugador('e5','d6'));assert.equal(r.ajedrez.get('d5'),undefined);assert.equal(r.ajedrez.get('d6').color,'w');});
test('Coronación ofrece cuatro piezas y respeta la subpromoción a caballo',()=>{const p=new PartidaPractica();serie(p,['a2a4','h7h5','a4a5','h5h4','a5a6','h4h3','a6b7','h3g2']);assert.deepEqual([...p.promociones('b7','a8')].sort(),['b','n','q','r']);assert.ok(p.moverJugador('b7','a8','n'));assert.equal(p.ajedrez.get('a8').type,'n');});
test('Detecta mate, bloquea nuevas jugadas y el PGN incluye el resultado',()=>{const p=new PartidaPractica();serie(p,['f2f3','e7e5','g2g4','d8h4']);assert.equal(p.terminada,true);assert.equal(p.estado().resultado,'0-1');assert.equal(p.moverJugador('a2','a3'),false);assert.match(p.pgn(),/0-1\s*$/);});
test('Conservar todas las jugadas mantiene la repetición al recargar',()=>{const p=new PartidaPractica();serie(p,['g1f3','g8f6','f3g1','f6g8','g1f3','g8f6','f3g1','f6g8']);const r=PartidaPractica.recuperar(p.guardar());assert.equal(r.terminada,true);assert.match(r.estado().texto,/repetición/);assert.equal(r.estado().resultado,'1/2-1/2');});
test('Rendición y PGN se conservan; deshacer permite continuar',()=>{const p=new PartidaPractica('b','suave');serie(p,['e2e4','e7e5']);p.rendirse();const r=PartidaPractica.recuperar(p.guardar());assert.equal(r.estado().resultado,'1-0');assert.match(r.pgn(),/1-0\s*$/);assert.ok(r.deshacer());assert.equal(r.terminada,false);});
test('Recuperación rechaza JSON con jugadas ilegales, opciones inválidas o continuación después del mate',()=>{const b=new PartidaPractica().guardar();for(const v of [null,{}, {...b,nivel:'inexistente'},{...b,color:'x'},{...b,jugadas:['e2e9']},{...b,jugadas:['f2f3','e7e5','g2g4','d8h4','a2a3']}])assert.equal(PartidaPractica.recuperar(v),null);});
test('Suave sólo elige respuestas legales; otros niveles usan la jugada del motor',()=>{const p=new PartidaPractica('b','suave');const uci=respuestaSuave(p,'e2e4',()=>0);assert.ok(p.esLegal(uci));assert.notEqual(uci,'e2e4');assert.equal(respuestaSuave(new PartidaPractica('b','club'),'e2e4',()=>0),'e2e4');});
class WorkerFalso extends EventTarget{commands=[];terminado=false;postMessage(c){this.commands.push(c);if(c==='uci')queueMicrotask(()=>this.emitir('uciok'));if(c==='isready')queueMicrotask(()=>this.emitir('readyok'));}terminate(){this.terminado=true;}emitir(data){this.dispatchEvent(new MessageEvent('message',{data}));}}
test('Motor confirma carga, manda historial y espera bestmove definitivo en lugar de aplicar PV parcial',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;const pending=m.buscar(['e2e4'],'club');await new Promise(resolve=>setImmediate(resolve));w.emitir('info depth 4 score cp 0 pv c7c5');w.emitir('bestmove e7e5 ponder g1f3');assert.equal(await pending,'e7e5');assert.ok(w.commands.includes('position startpos moves e2e4'));assert.ok(w.commands.includes('setoption name Skill Level value 4'));m.destruir();});
test('Destruir durante una búsqueda cancela la promesa y descarta bestmove tardío',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;const pendiente=m.buscar([],'suave');await new Promise(resolve=>setImmediate(resolve));const rechazada=assert.rejects(pendiente,e=>e.name==='AbortError');m.destruir();w.emitir('bestmove e2e4');await rechazada;assert.equal(w.terminado,true);});
test('Motor recupera un fallo de carga sin promesas que queden esperando',async()=>{const w=new WorkerFalso();w.postMessage=function(c){this.commands.push(c);};const m=new MotorPractica(()=>w,10);await assert.rejects(m.listo,/tardó demasiado/);assert.equal(w.terminado,true);});
test('Motor abandona una búsqueda sin respuesta y devuelve un error recuperable',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w,1000,10);await m.listo;await assert.rejects(m.buscar([],'club'),/no respondió/);assert.equal(w.terminado,true);});
test('Pedir pista usa fuerza alta sin cambiar el nivel permanente del bot',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;const p=m.buscar([],'suave',true);await new Promise(resolve=>setImmediate(resolve));w.emitir('bestmove e2e4');await p;const b=m.buscar(['e2e4'],'suave');await new Promise(resolve=>setImmediate(resolve));w.emitir('bestmove e7e5');await b;assert.ok(w.commands.includes('setoption name Skill Level value 20'));assert.ok(w.commands.includes('setoption name Skill Level value 0'));m.destruir();});
test('Error del Worker durante la búsqueda cancela, cierra el motor y permite mostrar reintento',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;const p=m.buscar([],'club');await new Promise(resolve=>setImmediate(resolve));const rechazo=assert.rejects(p,/No se pudo iniciar/);w.dispatchEvent(new Event('error',{cancelable:true}));await rechazo;assert.equal(w.terminado,true);});

test('Un Worker que falla estando inactivo devuelve el error en la siguiente búsqueda, sin dejar al bot detenido',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;w.dispatchEvent(new Event('error',{cancelable:true}));await assert.rejects(m.buscar([],'club'),/No se pudo iniciar/);assert.equal(w.terminado,true);});
