const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {Chess}=require('chess.js');const {DATOS_BOTS_PRACTICA,PartidaPractica,respuestaSuave}=require('../lib/partidaPractica.ts');const {MotorPractica}=require('../lib/motorPractica.ts');const {jugadasFrancesa}=require('../lib/francesa.ts');const {respuestaAtacante}=require('../lib/estiloBot.ts');
test('Víctor tiene 2150 Elo objetivo y siempre es el rival negro para jugar la Francesa',()=>{assert.equal(DATOS_BOTS_PRACTICA.victor.elo,2150);const p=new PartidaPractica('w','club','victor');assert.equal(p.turnoJugador,true);assert.ok(p.pgn().includes('Black "Víctor Terminator (aprox. 2150)"'));assert.throws(()=>new PartidaPractica('b','club','victor'),/negras/);assert.equal(PartidaPractica.recuperar({...p.guardar(),color:'b'}),null);});
test('Víctor se recupera como Víctor con su historial francés y conserva deshacer',()=>{const p=new PartidaPractica('w','club','victor');p.ajedrez.move('e4');p.ajedrez.move('e6');const r=PartidaPractica.recuperar(JSON.parse(JSON.stringify(p.guardar())));assert.equal(r.perfil,'victor');assert.equal(r.color,'w');assert.deepEqual(r.jugadas,['e2e4','e7e6']);assert.ok(r.deshacer());});
test('El perfil de Víctor no hereda jugadas aleatorias del nivel suave',()=>{const p=new PartidaPractica('w','suave','victor');p.moverJugador('e2','e4');assert.equal(respuestaSuave(p,'e7e6',()=>0),'e7e6');});
test('Francesa construye e6/d5; el rival puede abrir con e4, d4, c4 o Cf3',()=>{for(const san of ['e4','d4','c4','Nf3']){const c=new Chess();c.move(san);assert.deepEqual(jugadasFrancesa(c),['e7e6']);}const c=new Chess();for(const san of ['e4','e6','d4'])c.move(san);assert.deepEqual(jugadasFrancesa(c),['d7d5']);});
test('Francesa reacciona a Avance, Winawer, Tarrasch y Cambio con jugadas legales',()=>{for(const [blanca,respuesta] of [['e5','c7c5'],['Nc3','f8b4'],['Nd2','c7c5'],['exd5','e6d5']]){const c=new Chess();for(const san of ['e4','e6','d4','d5',blanca])c.move(san);assert.deepEqual(jugadasFrancesa(c),[respuesta]);c.move(respuesta);const blancaSiguiente=c.moves()[0];c.move(blancaSiguiente);assert.equal(jugadasFrancesa(c),undefined);}});
test('Un jaque temprano se responde sin forzar la variante de apertura',()=>{const c=new Chess();for(const san of ['e4','e6','d4','d5','Bb5+'])c.move(san);assert.equal(c.isCheck(),true);assert.equal(jugadasFrancesa(c),undefined);});
const posicionAtaque=()=>new Chess('rnbqkbnr/pppp1ppp/8/4p3/4P3/3P4/PPP2PPP/RNBQKBNR b KQkq - 0 2');
const variante=(uci,valor,profundidad=10,tipo='cp')=>({uci,valor,profundidad,tipo});
test('Estilo atacante prioriza un jaque sólo cuando su evaluación es cercana',()=>{const c=posicionAtaque();assert.equal(respuestaAtacante(c,'g8f6',[variante('g8f6',20),variante('f8b4',10)]),'f8b4');assert.equal(respuestaAtacante(c,'g8f6',[variante('g8f6',20),variante('f8b4',-100)]),'g8f6');assert.equal(respuestaAtacante(c,'g8f6',[variante('g8f6',20),variante('f8b4',10,4)]),'g8f6');});
test('El estilo respeta mate, restricciones de apertura y jugadas legales',()=>{const c=posicionAtaque();assert.equal(respuestaAtacante(c,'g8f6',[variante('g8f6',3,10,'mate'),variante('f8b4',10)]),'g8f6');assert.equal(respuestaAtacante(c,'g8f6',[variante('g8f6',20),variante('f8b4',10)],['g8f6']),'g8f6');assert.equal(respuestaAtacante(c,'g8f6',[variante('g8f6',20),variante('a8a1',20)]),'g8f6');});
class WorkerFalso extends EventTarget{commands=[];postMessage(c){this.commands.push(c);if(c==='uci')queueMicrotask(()=>this.emitir('uciok'));if(c==='isready')queueMicrotask(()=>this.emitir('readyok'));}terminate(){}emitir(data){this.dispatchEvent(new MessageEvent('message',{data}));}}
async function pedir(w,m,history,pista,options,uci){w.commands=[];const p=m.buscar(history,'club',pista,options);await new Promise(r=>setImmediate(r));w.emitir('bestmove '+uci);await p;return [...w.commands];}
test('Motor usa 2150 Elo y MultiPV atacante; pistas, Fonchi y práctica libre restauran la configuración',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;try{let c=await pedir(w,m,['e2e4'],false,{elo:2150,estiloAtaque:true,searchmoves:['e7e6']},'e7e6');assert.ok(c.includes('setoption name UCI_Elo value 2150'));assert.ok(c.includes('setoption name UCI_LimitStrength value true'));assert.ok(c.includes('setoption name MultiPV value 4'));assert.ok(c.includes('go movetime 1000 searchmoves e7e6'));c=await pedir(w,m,[],true,{elo:2150,estiloAtaque:true},'e2e4');assert.ok(c.includes('setoption name UCI_LimitStrength value false'));assert.ok(c.includes('setoption name MultiPV value 1'));c=await pedir(w,m,['e2e4'],false,{elo:2000,searchmoves:['g7g6']},'g7g6');assert.ok(c.includes('setoption name UCI_Elo value 2000'));c=await pedir(w,m,['e2e4'],false,{},'e7e5');assert.ok(c.includes('setoption name UCI_LimitStrength value false'));await assert.rejects(m.buscar([], 'club',false,{elo:2400}),/Fuerza/);}finally{m.destruir();}});
test('MultiPV guarda evaluaciones exactas finales, descarta cotas y no mezcla búsquedas',async()=>{const w=new WorkerFalso(),m=new MotorPractica(()=>w);await m.listo;try{const p=m.buscar(['e2e4'],'club',false,{elo:2150,estiloAtaque:true});await new Promise(r=>setImmediate(r));w.emitir('info depth 10 multipv 1 score cp 20 nodes 200 pv g8f6');w.emitir('info depth 10 multipv 2 score cp 10 nodes 200 pv f8b4');w.emitir('info depth 4 score cp 100 pv g8f6');w.emitir('info depth 11 score cp 100 lowerbound pv g8f6');w.emitir('bestmove g8f6');await p;assert.equal(m.variantes.length,2);assert.equal(m.variantes.find(v=>v.uci==='g8f6').valor,20);await pedir(w,m,[],true,{},'e2e4');assert.deepEqual(m.variantes,[]);}finally{m.destruir();}});
