"use client";
import { useState } from "react";
import { ejecutarPruebaPegasus } from "@/lib/pruebaPegasus";
import { TableroMini } from "./TableroMini";
export function GuiaPegasus(){
  const [rapida,setRapida]=useState(true),[orden,setOrden]=useState<"atacante"|"atacada"|"alternar">("alternar");
  const [prueba,setPrueba]=useState<ReturnType<typeof ejecutarPruebaPegasus>|null>(null),[error,setError]=useState("");
  return <div className="mt-6 flex flex-col gap-5"><section className="panel p-5"><h2 className="font-semibold">Antes de la primera jugada</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm text-zinc-400"><li>Usá Chrome o Edge de computadora con Bluetooth encendido. Cargá el tablero y cerrá la app DGT Chess y otras pestañas conectadas.</li><li>Colocá las piezas según la posición registrada. Conectá Pegasus y esperá el aviso de que las piezas coinciden.</li><li>Para capturar, levantá las piezas y colocá la atacante en el destino. Podés retirar primero cualquiera de las dos. Para enrocar, mové primero el rey y completá la torre.</li><li>Si la captura admite varios destinos o coronás, confirmá la opción que muestra la pantalla. No se elige una jugada por azar.</li><li>Si se corta Bluetooth, reconectá y verificá las piezas. Si falta una jugada, agregala sin borrar el historial. Descargá el PGN al terminar.</li></ol><p className="mt-4 text-xs text-zinc-500">El sensor detecta presencia, no el tipo de pieza. Si intercambiás dos piezas sin cambiar la ocupación, la posición necesita revisión manual. <a className="text-blue-300 hover:underline" href="https://www.digitalgametechnology.com/products/home-use-e-boards/dgt-pegasus" target="_blank" rel="noreferrer">Guía del fabricante ↗</a></p></section>
    <details className="panel p-5"><summary className="font-semibold">Probar el registro sin conectar un tablero</summary><p className="mt-3 text-sm text-zinc-400">Prueba local de 33 medias jugadas, con capturas en distinto orden y enroque. No publica ni modifica partidas del club.</p><div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-xs text-zinc-400">Velocidad<select aria-label="Velocidad de la prueba Pegasus" className="mt-1 block rounded-lg border border-white/15 p-2" value={rapida?"rapida":"normal"} onChange={e=>setRapida(e.target.value==="rapida")}><option value="rapida">Jugadas rápidas seguidas</option><option value="normal">Con pausa entre jugadas</option></select></label><label className="text-xs text-zinc-400">Orden de captura<select aria-label="Orden de captura de la prueba Pegasus" value={orden} onChange={e=>setOrden(e.target.value as typeof orden)} className="mt-1 block rounded-lg border border-white/15 p-2"><option value="alternar">Alternar los dos órdenes</option><option value="atacante">Primero levantar la atacante</option><option value="atacada">Primero retirar la capturada</option></select></label><button className="button-primary" onClick={()=>{try{setPrueba(ejecutarPruebaPegasus(rapida,orden));setError("");}catch{setError("La prueba detectó una discrepancia en el registro.");setPrueba(null);}}}>Registrar partida de prueba</button></div>{error&&<p role="alert" className="mt-4 text-red-300">{error}</p>}{prueba&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p role="status" className="mb-3 text-sm text-emerald-300">Partida completa: {prueba.jugadas.length} medias jugadas registradas, sin pérdidas.{prueba.confirmaciones>0?` Se simuló ${prueba.confirmaciones} confirmación del operador ante una jugada ambigua.`:""}</p><div className="max-w-80"><TableroMini fen={prueba.fen}/></div></div><div><label className="text-xs text-zinc-400">PGN reconstruido<textarea readOnly value={prueba.pgn} aria-label="PGN de la prueba Pegasus" className="mt-2 h-60 w-full rounded-lg border border-white/15 p-3 font-mono text-xs"/></label></div></div>}</details>
  </div>;
}
