import type { PerfilBot } from "./partidaPractica";
export type EmocionBot="esperando"|"pensando"|"captura"|"jaque"|"amenazado"|"victoria"|"derrota"|"tablas"|"perdida"|"dudosa"|"risa"|"elogio"|"charla";
const FRASES:Record<PerfilBot,Record<EmocionBot,string>>={
  fonchi:{perdida:"¡Mi pieza! Hipo, alcanzame un pañuelo…",dudosa:"¿Esa basura vas a jugar?",risa:"¡Jajaja! Hasta el hipo se está riendo.",elogio:"Gracias. El hipo también tiene sus momentos.",charla:"El hipo parece tranquilo… pero te está mirando.",esperando:"Vos ocupá el centro. El hipo espera acá atrás.",pensando:"Shhh… el hipo está pensando.",captura:"Un bocadito para el hipopótamo.",jaque:"¡Se despertó el hipo!",amenazado:"Pará, que me hacés levantar al hipo.",victoria:"El hipo esperó su momento.",derrota:"Hoy el hipo tenía sueño. ¿Revancha?",tablas:"El hipo y yo firmamos la paz."},
  victor:{perdida:"Daño detectado. Esa pieza no estaba en el presupuesto.",dudosa:"Error humano detectado.",risa:"JA. JA. JA. Módulo de humor activado.",elogio:"Reconocimiento recibido. Continuaré con la misión.",charla:"Puedo esperar. Mi batería dura más que tu defensa.",esperando:"Objetivo: tu rey.",pensando:"Analizando tu próxima equivocación…",captura:"Pieza eliminada.",jaque:"Objetivo localizado.",amenazado:"Amenaza detectada. Recalculando.",victoria:"Misión cumplida.",derrota:"Volveré.",tablas:"Empate registrado. La misión continúa."},
  matias:{perdida:"Bueno… era un sacrificio. Creo.",dudosa:"Con ese viento, se te vuela una pieza.",risa:"¡Jajaja! Y eso que hoy ni miré el celular.",elogio:"¡Gracias! Algún recurso tenía que aparecer.",charla:"No estudié, pero alguna idea se me va a ocurrir.",esperando:"Un peón menos, unas cuantas ideas más.",pensando:"Pará… algún recurso tiene que haber.",captura:"Este peón tenía viento a favor.",jaque:"¿Y si complicamos un poquito?",amenazado:"Todavía me queda un recurso.",victoria:"Y eso que dicen que no estudio…",derrota:"Me ganaste. Pero la próxima se complica.",tablas:"Nos quedó una linda pelea. ¿Otra?"},
  stockfish:{perdida:"¡Buena captura! Me toca buscar otro plan.",dudosa:"Esa idea tiene sus riesgos.",risa:"¡Jajaja! La revancha viene incluida.",elogio:"¡Gracias! Vos también estás dando pelea.",charla:"¿Probamos una idea nueva?",esperando:"Probá una idea. Hay tiempo.",pensando:"Buscando la mejor respuesta…",captura:"Una pieza menos, un plan nuevo.",jaque:"¡Atención al rey!",amenazado:"Buen jaque. Veamos cómo seguimos.",victoria:"¿Probamos otra partida?",derrota:"Bien jugado. ¡Vamos por la revancha!",tablas:"Ni para vos ni para mí. Otra partida."},
};
const EXTRAS:Partial<Record<PerfilBot,Partial<Record<EmocionBot,string[]>>>>={
  fonchi:{esperando:["Sin apuro. El hipo tiene paciencia.","No es siesta. Es estrategia."],pensando:["Un segundo… estamos consultando con el hipo."],captura:["El hipo pidió otra porción."],charla:["Si nos dejás tranquilos, armamos nuestro ranchito."],risa:["¡Jajaja! Se ríe bajito para no despertar al hipo."]},
  victor:{esperando:["Tu rey sigue en mi radar.","Modo ataque: activado."],pensando:["Calculando ruta hacia tu rey."],captura:["Objetivo retirado del tablero."],charla:["No necesito café. Necesito líneas abiertas."],risa:["Humor procesado. Ja. Ja."]},
  matias:{esperando:["Un peón va y viene. Las ideas quedan.","Por algún lado se puede complicar."],pensando:["A ver… esto tiene que tener algún truquito."],captura:["Viento a favor. Vamos de nuevo."],charla:["Dicen que no estudio. Yo no confirmo ni desmiento."],risa:["¡Jajaja! Esto no me lo sopló el celular."]},
};
export function fraseBot(perfil:PerfilBot,emocion:EmocionBot,variacion=0){const frases=[FRASES[perfil][emocion],...(EXTRAS[perfil]?.[emocion]??[])];return frases[Math.abs(Math.trunc(variacion))%frases.length];}
